version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vodka
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped
    networks:
      - vodka-network
    command: >
      sh -c "until nc -z postgres 5432; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      until nc -z redis 6379; do
        echo 'Waiting for Redis to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL and Redis are ready!';
      npx prisma migrate deploy && node dist/src/main.js"

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vodka-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - vodka-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  vodka-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: